### ISSUE TITLE
AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'

### ISSUE THREAD

**Issue by Hass1000** [RuslanUC/aio-hcaptcha#10]
Getting this error when trying to run:

```py
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\python\test.py", line 7, in <module>
    from async_hcaptcha import AioHcaptcha
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\async_hcaptcha\__init__.py", line 1, in <module>
    from .asynchcaptcha import AioHcaptcha
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\async_hcaptcha\asynchcaptcha.py", line 22, in <module>
    hcaptcha_challenger.logger.remove() # TODO: Redirect logs from loguru to logging or use loguru instead of logging
AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'
```

**Comment by RuslanUC** [comment]
Try to run `pip install --upgrade hcaptcha_challenger`

**Comment by Hass1000** [comment]
yeah works thanks, ty
