### ISSUE TITLE
How to fix this error

### ISSUE THREAD

**Issue by andewq** [RuslanUC/aio-hcaptcha#4]
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from async_hcaptcha import AioHcaptcha
  File "/home/runner/AltruisticWoefulCodewarrior/venv/lib/python3.8/site-packages/async_hcaptcha/__init__.py", line 1, in <module>
    from .asynchcaptcha import AioHcaptcha
  File "/home/runner/AltruisticWoefulCodewarrior/venv/lib/python3.8/site-packages/async_hcaptcha/asynchcaptcha.py", line 20, in <module>
    from .autosolver import AutoSolver, AutoSolverException
  File "/home/runner/AltruisticWoefulCodewarrior/venv/lib/python3.8/site-packages/async_hcaptcha/autosolver.py", line 1, in <module>
    from ._autosolver import PluggableObjects, YOLO, PluggableONNXModels
  File "/home/runner/AltruisticWoefulCodewarrior/venv/lib/python3.8/site-packages/async_hcaptcha/_autosolver.py", line 15, in <module>
    import cv2
  File "/home/runner/AltruisticWoefulCodewarrior/venv/lib/python3.8/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by RuslanUC** [comment]
What system do you using?

**Comment by andewq** [comment]
I use windows and everything works fine there, but I need my project to run 24/7, for that I need a host. I tried heroku, but my project size is over 500 mb. After that I tried replit and got this error

**Comment by RuslanUC** [comment]
Click on three dots in files tab, click "show hidden files", open replit.nix and paste this:
```
{ pkgs }: {
  deps = [
    pkgs.nano
    pkgs.unzip
    pkgs.wget
    pkgs.python38Full
    
    pkgs.chromium
    pkgs.chromedriver
    pkgs.nss
    pkgs.nspr
    pkgs.xorg.libxcb
    pkgs.dbus
    pkgs.libGL
  ];
  env = {
    PYTHON_LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
      # Needed for pandas / numpy
      pkgs.stdenv.cc.cc.lib
      pkgs.zlib
      # Needed for pygame
      pkgs.glib
      # Needed for matplotlib
      pkgs.xorg.libX11

      pkgs.chromium
      pkgs.chromedriver
      pkgs.libGL
    ];
    LD_LIBRARY_PATH="${pkgs.glib.out}/lib:${pkgs.nss.out}/lib:${pkgs.nspr.out}/lib:${pkgs.xorg.libxcb.out}/lib:${pkgs.dbus.out}/lib:${pkgs.libGL.out}/lib:$LD_LIBRARY_PATH";
    PYTHONBIN = "${pkgs.python38Full}/bin/python3.8";
    LANG = "en_US.UTF-8";
  };
}
```
It will install all needed libraries, but it can raise ImportError with config.py. I don't know, how to fix this error, but after several attempts it started. Maybe error can be fixed by moving opencv (cv2) directory to one directory with your script (I'll try this tomorrow).

**Comment by RuslanUC** [comment]
Follow this instructions: https://github.com/RuslanUC/aio-hcaptcha/releases/tag/opencv-replit

**Comment by andewq** [comment]
Thanks
Everything is working great now.
