### ISSUE TITLE
Async eventloop SSL Error when calling solver.solve()

### ISSUE THREAD

**Issue by FuckingToasters** [RuslanUC/aio-hcaptcha#9]
```py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Downloads\Projects\discordphoneverify_public\new version\main.py", line 181, in verify
    CAPTCHATOKEN = bypasscap.hcaptcha()
  File "D:\Downloads\Projects\discordphoneverify_public\new version\plugins\captcha\hcaptchasolver.py", line 43, in hcaptcha
    CAPTCHASOLUTION = asyncio.run(capsolver.Solver.solution())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Downloads\Projects\discordphoneverify_public\new version\plugins\captcha\aiohcaptcha.py", line 12, in solution
    captcha_key = await solver.solve(retry_count=5)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\async_hcaptcha\asynchcaptcha.py", line 436, in solve
    if (answers := await self._question_callback(captcha["requester_question"]["en"], tasklist)) is None: # Get answers
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\async_hcaptcha\asynchcaptcha.py", line 349, in autosolve
    imgs.append(await getUrl(url, False))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\async_hcaptcha\utils.py", line 28, in getUrl
    async with sess.get(url) as resp:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 814, in run_in_executor    executor.submit(func, *args), loop=self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000017F319543A0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000017F50E7C340>, 63006.562)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x0000017F50E7CA00>, 63010.906)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000017F31954430>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000017F50E6F850>
transport: <_ProactorSocketTransport fd=1308 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000017F314D3700>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
    self._ssl_protocol._start_shutdown()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
    self._write_appdata(b'')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
    self._process_write_backlog()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
    self._fatal_error(exc, 'Fatal error on SSL transport')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
    self._transport._force_close(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000017F50EB3AC0>
transport: <_ProactorSocketTransport fd=-1 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000017F314D3700>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
    self._ssl_protocol._start_shutdown()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
    self._write_appdata(b'')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
    self._process_write_backlog()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
    self._fatal_error(exc, 'Fatal error on SSL transport')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
    self._transport._force_close(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
I don't rly understand why this happen....

**Comment by RuslanUC** [comment]
Do you use proxies?

**Comment by FuckingToasters** [comment]
no, i ran it without proxy

**Comment by RuslanUC** [comment]
Does this error keep appearing?

**Comment by FuckingToasters** [comment]
> Does this error keep appearing?

yes, direclty after first execution everytime i run it.

**Comment by RuslanUC** [comment]
Can you send your code?

**Comment by FuckingToasters** [comment]
> Can you send your code?

```py
from async_hcaptcha import AioHcaptcha # pip install async-hcaptcha
from plugins.configuration.load import config
_, _, SITEKEY, _, _, _, _, _, _, _, _ = config().loadconfig()

class Solver:
    async def solution():
        captcha_key = None

        for _ in range(3):
            solver = AioHcaptcha(SITEKEY, "https://discord.com/api/v9/users/@me/phone", {"executable_path": "driver/chromedriver.exe"})
            try:
                captcha_key = await solver.solve(retry_count=5)
                break

            except KeyError: continue
        return captcha_key
```

**Comment by RuslanUC** [comment]
Can you try to run it on different system/computer?

**Comment by FuckingToasters** [comment]
> Can you try to run it on different system/computer?

okay lemme try

**Comment by FuckingToasters** [comment]
on ym rdp i now get this issue: 
```py
Exception in thread Thread-1 (verify):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\collection\discordphoneverify_public\new version\main.py", line 181, in verify
    CAPTCHATOKEN = bypasscap.hcaptcha()
  File "C:\Users\Administrator\Desktop\collection\discordphoneverify_public\new version\plugins\captcha\hcaptchasolver.py", line 41, in hcaptcha
    import plugins.captcha.aiohcaptcha as capsolver
  File "C:\Users\Administrator\Desktop\collection\discordphoneverify_public\new version\plugins\captcha\aiohcaptcha.py", line 1, in <module>
    from async_hcaptcha import AioHcaptcha # pip install async-hcaptcha
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\async_hcaptcha\__init__.py", line 1, in <module>
    from .asynchcaptcha import AioHcaptcha
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\async_hcaptcha\asynchcaptcha.py", line 22, in <module>
    hcaptcha_challenger.logger.remove() # TODO: Redirect logs from loguru to logging or use loguru instead of logging
AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'
```

**Comment by RuslanUC** [comment]
Try to reinstall hcaptcha_challenger

**Comment by FuckingToasters** [comment]
> Try to reinstall hcaptcha_challenger

now same issue as above, switching to rdp didn't solved it (https://github.com/RuslanUC/aio-hcaptcha/issues/9#issue-1434977833)

**Comment by FuckingToasters** [comment]
@RuslanUC u here?

**Comment by RuslanUC** [comment]
Yes, i testing it on different systems. So far everything is working

**Comment by FuckingToasters** [comment]
> Yes, i testing it on different systems. So far everything is working

i tried it on my main pc first time and then on a rdp, both times same issue

**Comment by Pluzdev** [comment]
Same for me

**Comment by FuckingToasters** [comment]
> Yes, i testing it on different systems. So far everything is working

look, i'm not the only one with this issue
